[theme]
primaryColor = "#00a884"
backgroundColor = "#f1f8f6"
secondaryBackgroundColor = "#e8f5e9"
textColor = "#333333"
font = "sans serif"

[client]
showErrorDetails = true
encoding = "utf-8"

[server]
port = 8501
headless = true
